### ISSUE TITLE
RTL8125 any workaround to prevent these steps everytime i start the machine ?

### ISSUE THREAD

**Issue by oianmol** [redcweed/z490#5]
2.5G Ethernet (must use attached patched kext) (must force select a speed -- which you need to do by going to System Preferences -> Network -> Ethernet -> Advanced -> Hardware -> Speed: (select 1000baset if you are using a 1000t bridge/router))

**Comment by planetwally** [comment]
hey @Anmol92verma this is a one time setting that you should not need to reset each time you restart. If you are having to reset it then there is something not right with your configuration and/or nvram that is not persisting the selected speed after a powercycle.

**Comment by oianmol** [comment]
Hi @redcweed i first set it to manual and it doesn't connect, but then i set it to automatic and it connects! , its the same every time i boot

**Comment by planetwally** [comment]
@Anmol92verma that's interesting, so when set for automatic it connects and works fine? are you using 1000t ethernet with the 2.5g card? same exact motherboard and same .kext for the ethernet card?

**Comment by oianmol** [comment]
@redcweed I successfully updated to big sur and oc 0.6.2 https://github.com/Anmol92verma/z490_opencore_msi
